### ISSUE TITLE
New single-select InputDropdown variant

### ISSUE THREAD

**Issue by cathystoli** [chanzuckerberg/sci-components#337]
**Component Name:** InputDropdown
**Component Requirements:** - New component variation, specific parameters as below
- sdsType: single-select
- sdsStyle: minimal
- Details: on

**Design specs:** https://www.figma.com/file/RAIg2Gzsw2QylzY28LYsl5/InputDropdown-Exploration?node-id=55%3A539&t=ZFHEOb3IWQMPkJqf-1
**Team(s) Requesting:** CZID
**Component Needed By:** This is part of the Heatmap - Move Filters to the left project. I will share the eng point of contact after handoff

**Plan Details:**
- There is a version of this that exists but does not match the full requirements, we will take what exists in the code and updating it 

- [x] #343 blocker for this ticket 
- [ ] Eng implementation - @liaprins this ticket

**Comment by cathystoli** [comment]
@clarsen-czi can you review the request above? It would be good to get your thoughts on the broader use for this change

**Comment by clarsen-czi** [comment]
@cathystoli Kev and I chatted about this one before he posted to the SDS request channel and I let him know I thought it would make a good addition to SDS.

For context, it would be an additional variant of the minimal dropdown input allowing for the ability to include text with additional details as part of the input (such as what or how many options have been selected in the accompanying dropdown menu). Currently the rounded and square dropdown inputs have this ability, but the minimal version does not, so this is just expanding that ability to the minimal version.

LMK if you're looking for any more details about broader implications!

**Comment by liaprins** [comment]
> ability to include text with additional details as part of the input... (such as 
> 1. what or 
> 2. how many options have been selected in the accompanying dropdown menu

@clarsen-czi Do the different examples you listed above (I split into numbered list of "1" and "2" above) need to each be a distinct variant? Or there just needs to be one variant that can accommodate text in general? If the former, are there any other usecases that would warrant their own variant for this component as well (in addition to 1 and 2 above)? Thanks!

**Comment by tihuan** [comment]
@clarsen-czi 

Some quick questions 😄 🙏 

1. In the [design](https://www.figma.com/file/v8T3vabzkmbvH71sQ1EXzh/Kevin---Heatmap-Filters-Redesign?node-id=1047%3A35901&t=6w4yzPlbDqUARD6f-1), the minimal InputDropdown has the detail/count in a new line, is that always the case or only when they can't fit on one line?

<img width="520" alt="Screenshot 2023-02-01 at 10 24 17 AM" src="https://user-images.githubusercontent.com/6309723/216129966-f07e61f3-0b6e-4785-a70d-e2d46ac888ed.png">

2. Currently in storybook minimal "technically" has details/count, it's just that everything is on the same line and there's `:` to separate label from details/count. So I suppose the diff we want to make are:

1. For Minimal version, no `:` and details/count is always on the second line?

<img width="151" alt="Screenshot 2023-02-01 at 10 21 18 AM" src="https://user-images.githubusercontent.com/6309723/216130395-a00a5a2e-b0a6-4290-ba2b-5028f3476711.png">


Thank you!

**Comment by clarsen-czi** [comment]
@liaprins and @tihuan thanks for the questions! I didn't realize we already had a minimal `InputDropdown` with the option to include details/count on it. Seems like it was created using the pattern for the rounded and square variants even though we didn't have a design need for it. If you could remove that build and replace it with the design I've linked below, that'd be great!

For background: We've chatted about this as a design team and have determined that we actually have two different types of `InputDropdown` that are needed for our products. The first type of `InputDropdown` contains Labels and Values/Counts and the other type includes Values and Details about those values. We will work on refactoring our current `InputDropdown` component into these two types later this half, so keep an eye out for that.

For now, this project will just focus on updating the minimal variant of the existing `InputDropdown`, but for context, this build falls into that first type: Labels and Values (you'll notice I'm using the word "value" instead of "details" to try and align with this new `InputDropdown` paradigm I mentioned above).

Lia, to answer your question:

1. For now, let's only focus on a variant that accepts text. At this point, there's no product need for a minimal `InputDropdown` that accepts a count, so we'll build that option, if we decide it's needed, when we work on refactoring the entire `InputDropdown` component at a future date.

Timmy, to answer your questions:

1. The value text will always be on a new line
2. Go ahead and replace what currently exists in the codebase/Storybook for the minimal `InputDropdown ` with the designs I've linked below
3. Correct, no `:` and value is always on the second line

To help with the build I've put together a spec sheet in Figma which you can find [here](https://www.figma.com/file/RAIg2Gzsw2QylzY28LYsl5/InputDropdown-Exploration?node-id=55%3A539&t=cTFlMvZG8qvGV93F-1). Let me know if you have any additional questions as your working through it.

Thank you both!!

**Comment by tihuan** [comment]
- [ ]  Add value always as new line
- [ ] :hover and :active need grey background
- [ ] no `:` for minimal
- [ ] Add spacing around label and button according to Figma
- [ ] Add prop to allow wrapping and truncating - look at Table Cell for example

**Comment by cathystoli** [comment]
@masoudmanson to create a bug ticket for what happened in CZID
