### ISSUE TITLE
Investigation into downloading SVG for heatmap

### ISSUE THREAD

**Issue by cathystoli** [chanzuckerberg/sci-components#561]

**Comment by tihuan** [comment]
Hey @masoudmanson can you share your discoveries here, so stakeholders can follow along too please 😄 ? Thanks so much!

PNG download should be straightforward, since there are existing npm libraries to convert DOM to PNG. 

One helpful thing Single Cell Team did was to add a custom css class names like `className="ignore-image-download"` on components in the DOM tree that we don't want to render in the downloaded image. So perhaps SDS Heatmap can expose a unique css class name for product team to use to ignore component in their DOM tree as well? e.g., `const HEATMAP_IGNORE_IMAGE_DOWNLOAD_CSS_CLASS = "sds-ignore-image-download"` or something better!

SVG is the hard part, since libraries can't convert DOM to native SVG elements. The best they can do is to use SVG ForeignObject wrapper on DOM elements, which will render the SVG in browsers, since browsers understand DOM, but it won't load the SVG in image processing softwares like https://inkscape.org/, which scientists use to edit the SVG before printing out huge posters for conferences

The solution Single Cell Team did for SVG is to manually create native SVG elements (squares, circles, texts, etc.) that look similar to their DOM element equivalent, so basically walk the DOM tree ourselves and emit custom SVG elements accordingly. Since SDS Heatmap won't know how to create custom SVG elements for the product's DOM tree, I think SDS Heatmap could probably help with walking the DOM tree and expose callback functions for the product to write custom SVG element for each DOM tree node or something?

**Comment by masoudmanson** [comment]
Hey @tihuan,

Thanks a bunch for sharing your approach – it's pretty clever.

I've been wrestling with the SVG/PNG export challenge, especially with the camera scroll effect in play. The fact that we're rendering only the visible section of the heatmap makes exporting a bit complex.

Here's what I've done: I added a download button to the SDS Heatmap demo. It lets users download the visible section as either SVG or PNG, depending on the renderer. I've also added a button to flip between SVG and Canvas rendering.

What's cool is that the current setup preserves heatmap styles and cell selections in the exported file, which would be a difficult thing to do if we want to recreate SVG elements based on the DOM tree.

Dealing with the camera scroll effect during SVG/PNG download is a bit challenging. We might need to temporarily turn off the camera scrolling, generate the export, and then switch the camera effect back on. For smaller to medium-sized heatmaps, that's no problem. But for the larger heatmaps where the renderer struggles to display all data cells on the screen, we might have to break the heatmap into smaller chunks and export each section separately. (I'm currently trying to figure out the optimal way to handle this task.)

I've rolled out these changes on the SDS Heatmap demo. Check it out here: [SDS Heatmap Demo](https://sds-heatmap.vercel.app/)

**Comment by masoudmanson** [comment]
![echarts (7)](https://github.com/chanzuckerberg/sci-components/assets/927990/36da88e7-472c-469d-8be8-20e2df2ee2c4)

**Comment by tihuan** [comment]
Thanks for the detailed update and updating the demo, @masoudmanson 😄 🙏 

Ah yes, sorry I forgot to add that CS Team (single cell team is now Cell Science Team, thus CS instead of SC 😆 ) only had to do the manual SVG element creation for the axis elements not the heatmap dots itself, so perhaps we don't have to worry about manually creating SVG elements in the SDS Heatmap Chart component at all, since this component doesn't know about the axis anyway lol WHEW!

Another observation CS Team has is that we switch from canvas mode to SVG mode temporarily when generating the images, because canvas dots are not vectors and get very blurry easily when zooming in. So since we need to re-render the dots in SVG when downloading, it makes sense to just temporarily disable camera effect to render the whole chart. And when dealing with bigger charts, we chunk them like you said!

As for chunking, it feels like the bottleneck is figuring out how to send subsets of passed in data to echarts to generate each subset image, and then ideally how to stitch all the subset images together in one SVG tree?

Another thing here is that the output SVG tree might need to be sent back to the user in a callback (maybe?), so they can combine the dot SVG tree we create with the axis presentation that they control to generate the final SVG image. Hope that makes sense!

Last thing is that when we temporarily switch from canvas mode to SVG mode, CS Team had to use MutationObserver to check if echart is done updating the DOM before parsing the DOM tree, so we don't risk generating images from incomplete DOM. So we might need to do that in SDS Heatmap Chart code too!
