### ISSUE TITLE
Unable to control InputText width

### ISSUE THREAD

**Issue by lanesawyer** [chanzuckerberg/sci-components#853]
**Describe the bug**
I was trying to make a component with two small text inputs:
![image](https://github.com/user-attachments/assets/28dac778-424f-4321-abd9-de3c6c1c5b6d)

**To Reproduce**
1. Go to an `InputText`
2. Try to style the width as you can do with the MUI text component (`<InputText sx={{ width: '64px' }} />`)
3. Notice that the width doesn't change

**Expected behavior**
I expected to be able to control the text input field's width similarly to how it's controlled in MUI.

**Comment by masoudmanson** [comment]
Hi @lanesawyer, 

The issue is due to a hardcoded minimum width of `160px` in the `InputText` component, which is causing the problem. I’ll check in with the design team to understand the reason behind this restriction and get back to you with a solution. My initial thought is that we may need to remove the `min-width` and allow users to define the width as needed.

Thanks for reporting this! 🙏🏻
